### ISSUE TITLE
RPC client 500 error : err: {"id":"go.micro.client","code":500,"detail":"none available","status":"Internal Server Error"}

### ISSUE THREAD

**Issue by ChengYayu** [micro/go-grpc#10]
The RPC client occasionally has a 500 error, sometimes 500 error, sometimes normal

```go
func RegisterCouponGRPCService(grpcAddr string) pb.CouponService {
	// var serviceName = "abox.marketing.srv.coupon"
	registry := mdns.NewRegistry(
		registry.Addrs(grpcAddr),
	)
	service := grpc.NewService(
		micro.Name("abox.marketing.srv.coupon.client"),
		micro.Version("0.1"),
		micro.Registry(registry),
	)
	service.Init()
	return pb.NewCouponService("abox.marketing.srv.coupon", service.Client())
}
```
we will new a rpc client in main.go like below

```go
once.Do(func() {
		//创建grpc服务单例
		CouponRPCS := services.RegisterCouponGRPCService(beego.AppConfig.String("grpc_server_url"))
}
``` 
in other files，we will use the CouponRPCS. then I get the error sometimes.

```go
err: {"id":"go.micro.client","code":500,"detail":"none available","status":"Internal Server Error"}
```

**Comment by asim** [comment]
The error implies there are no nodes in the registry. There's a related issue for client retries. You should `go get -u github.com/micro/go-grpc` and then see if the problem continues to present itself. If it does its likely related to the use of the mdns registry.

**Comment by ChengYayu** [comment]
@asim thanks for your reply! We did use the mdns registry, because I can't rely on third-party registries for irresistible reasons, such as: consul, so I used the mdns registry. Is there any problem with using the mdns registry in a production environment? Or is there a way to not apply the registry only use ip and port to complete the connection between the rpc client and the rpc server?

**Comment by asim** [comment]
mdns relies on multicast dns which is not supported by most cloud providers. It relies on being able to broadcast multicast packets on the network. 

My advice would be to choose an appropriate registry for your environment.
