### ISSUE TITLE
Issue load testing with some standard grpc tools

### ISSUE THREAD

**Issue by comtom** [micro/go-grpc#11]
I have a go-micro service running locally, registered in consul (which I use as service registry):

```
    2018/10/08 16:31:29 [DEBUG] http: Request PUT /v1/agent/check/pass/service:enta-nimax-b51023cb-cb2f-11e8-b79b-a08cfd74f549?note= (299.368µs) from=127.0.0.1:34708
    2018/10/08 16:31:38 [DEBUG] agent: Skipping remote check "serfHealth" since it is managed automatically
    2018/10/08 16:31:38 [DEBUG] agent: Service "dev-service-b51023cb-cb2f-11e8-b79b-a08cfd74f549" in sync
    2018/10/08 16:31:38 [DEBUG] agent: Check "service:dev-service-b51023cb-cb2f-11e8-b79b-a08cfd74f549" in sync
```

I tried to run a load test with a few standar tools to test grpc services. In particular with latest pre-built version of ghz downloaded from the download page and then ran:

```
$ ./ghz -proto="ProviderService/ProviderService.proto" -call="dev-service.GenerateShows" -d="{}" 127.0.0.1:34708 -insecure 

but failed with: **cannot find service "service:dev-service-b51023cb-cb2f-11e8-b79b-a08cfd74f549"**
```
Then tried with grpcurl:

`./grpcurl -plaintext  -d '{}'  localhost:35929 dev-service-b51023cb-cb2f-11e8-b79b-a08cfd74f549.GenerateShows
Error invoking method "dev-service-b51023cb-cb2f-11e8-b79b-a08cfd74f549.GenerateShows": failed to query for service descriptor "dev-service-b51023cb-cb2f-11e8-b79b-a08cfd74f549": server does not support the reflection API`

the issue seem to be that reflection is not enabled in the service. Wouldn't be nice that reflection is done inside go-grpc?

there is some info about how to do it in the official grpc repo:
https://github.com/grpc/grpc-go/tree/master/reflection

and here an example in a service made by ghz developer:
https://github.com/nzoschke/omgrpc/commit/07b3fb4e56d3464a52f8bc21d2925072d401adfd

**Comment by asim** [comment]
I think it's not possible for us to support this. We use the UnknownMethodHandler for registering our own versions of handlers with the grpc server. You can look at the grpc [server](https://github.com/micro/go-plugins/tree/master/server/grpc) if you want to try.
