### ISSUE TITLE
connection pool does not work in grpc mode

### ISSUE THREAD

**Issue by ginuerzh** [micro/go-grpc#13]
I have two grpc services created by `grpc.NewSerivce`, the first api service calls the second service.
The grpc client creates a new connection for each call even though I set the `--client_pool_size` option.

**Comment by vtolstov** [comment]
connection pool only works for default server and default transport.

**Comment by asim** [comment]
@vtolstov please don't answer questions incorrectly.

@ginuerzh the connection pool works much like memcached and others where its non-blocking. In the event a connection exists in the pool its used, if the connection is in use a new one will be created. When the connection is released it will try to put it back in the pool. In event the pool is full it will throw away the connection. If a connection has outlived its ttl then a new one must also be created.

**Comment by ginuerzh** [comment]
Does Micro support grpc multiplexing?

**Comment by asim** [comment]
No, feel free to implement here https://github.com/micro/go-plugins/tree/master/client/grpc

Marking as resolved.
