### ISSUE TITLE
gRPC middleware & SSL

### ISSUE THREAD

**Issue by iSynth** [micro/go-grpc#16]
Hello! 

I have not found any forum where I could ask about micro/go-grpc.

Is there [gRPC middleware](https://github.com/grpc-ecosystem/go-grpc-middleware) support? I want to add my interceptors as well a SSL traffic encryption.

**Comment by asim** [comment]
There's no current support for interceptors. You can PR a solution to add the options if you like much like TLS.

**Comment by ByteFlinger** [comment]
I have pushed a PR (https://github.com/micro/go-plugins/pull/293) to the micro plugins repo to add support for custom `grpc.ServerOption`.

I think this should resolve this issue

**Comment by asim** [comment]
Great. Closing the issue.
