### ISSUE TITLE
grpc server always register to consul with name go-server-*

### ISSUE THREAD

**Issue by wlibo666** [micro/go-grpc#2]
I build code use cmd: go build in directory: github.com/micro/go-grpc/examples/greeter/server.
then I run it: ./server.
it output like below:
[wcy@wcy server]$ ./server 
2017/08/16 15:19:14 Listening on [::]:44890
2017/08/16 15:19:14 Broker Listening on [::]:42220
2017/08/16 15:19:14 Registering node: go-server-34f6b31e-8253-11e7-a600-000c2960f9a7
^C2017/08/16 15:19:19 Deregistering node: go-server-34f6b31e-8253-11e7-a600-000c2960f9a7

but the name of micro service is not go-server in code:
service := grpc.NewService(
		micro.Name("go.micro.srv.greeter"),
		micro.RegisterTTL(time.Second*30),
		micro.RegisterInterval(time.Second*10),
	)

I found that the server is struct grpcServer,but is call rpcServer's function Register().
how can I solve it?

**Comment by asim** [comment]
How are you running this example?

```
git clone https://github.com/micro/go-grpc
cd github.com/micro/go-grpc/examples/greeter
go run server/main.go
```

The output I have
```
2017/08/16 08:38:07 Listening on [::]:57504
2017/08/16 08:38:07 Broker Listening on [::]:57505
2017/08/16 08:38:07 Registering node: go.micro.srv.greeter-d84cf822-8255-11e7-aa0b-f40f242f6897
```

**Comment by wlibo666** [comment]
I am not run: go get -u,maybe other package is too old. I will update them to try again,thanks.

**Comment by wlibo666** [comment]
I update dependent package,and run it in window git bash,it works normally.

enviroment like that:
OS: window 10
git bash 4.3.46

wlibo@DESKTOP-BQ6070U MINGW64 /e/WorkCode/src/github.com/micro/go-grpc/examples/greeter/server (master)
$ ll
total 27660
-rw-r--r-- 1 wlibo 197609      768 8月  16 16:01 main.go
drwxr-xr-x 1 wlibo 197609        0 8月  16 16:01 proto/
-rw-r--r-- 1 wlibo 197609 14056006 8月  16 16:02 server
-rwxr-xr-x 1 wlibo 197609 14261248 8月  16 17:01 server.exe*

wlibo@DESKTOP-BQ6070U MINGW64 /e/WorkCode/src/github.com/micro/go-grpc/examples/greeter/server (master)
$ ./server.exe
2017/08/16 17:01:50 Listening on [::]:51394
2017/08/16 17:01:50 Broker Listening on [::]:51395
2017/08/16 17:01:50 Registering node: go.micro.srv.greeter-8a4bc3ff-8261-11e7-ab54-448a5b42d04f

but another environment is not normal.
windows and vm os (centos 6.8) use the same GOPATH directory and source code.

windown 10's disk(directory) is mounted on vmware os (centos6.8)

vmware 11.1.2
centos 6.8

[wcy@wcy server]$ go build
[wcy@wcy server]$ ./server
2017/08/16 17:04:54 Listening on [::]:33725
2017/08/16 17:04:54 Broker Listening on [::]:35616
2017/08/16 17:04:54 Registering node: go-server-f86817e4-8261-11e7-bef7-000c2960f9a7
^C2017/08/16 17:04:58 Deregistering node: go-server-f86817e4-8261-11e7-bef7-000c2960f9a7


windows           vmware( mount on centos6.8)
   |                         |
   |__disk gopath__|

**Comment by wlibo666** [comment]
I am sorry,I set environment variable like below in my vm os,
MICRO_CLIENT=grpc
MICRO_SERVER=grpc

when I unset it, the program work normally.
thanks for you help !!!
