### ISSUE TITLE
grpc.NewService() not running TLS on server?

### ISSUE THREAD

**Issue by GeorgeBills** [micro/go-grpc#21]
I'm running both a go-micro GRPC server (`github.com/micro/go-grpc.NewService()`) and a "plain" GRPC server (`google.golang.org/grpc.NewServer()`), and passing them both the same certificate.

I'm following the example service at https://github.com/micro/go-grpc/blob/master/examples/greeter/server/main.go and subbing in ` grpc.WithTLS(tlsConfig)` as per https://github.com/micro/go-grpc/issues/4#issuecomment-369528973.

openssl s_client claims that the "plain" GRPC server is using TLS, while the go-micro GRPC server isn't, and I'm getting TLS error messages ("handshake failed") on go-micro clients connecting to the server:

> {"id":"","code":0,"detail":"all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\"","status":""}

Am I doing something wrong here? Apologies in advance if this is PEBKAC.

Reproduction code is below:

	package main

	import (
		"crypto/tls"
		"log"
		"net"

		"google.golang.org/grpc"
		"google.golang.org/grpc/credentials"

		microgrpc "github.com/micro/go-grpc"
		"github.com/micro/go-micro"
		"github.com/micro/go-micro/server"
	)

	func main() {
		certificate, err := tls.LoadX509KeyPair("assets/my.crt", "assets/my.key")
		if err != nil {
			log.Fatal(err)
		}

		// micro GRPC server
		// openssl.exe s_client -connect 127.0.0.1:5678
		// no peer certificate available
		tlsConfig := &tls.Config{
			Certificates: []tls.Certificate{certificate},
		}
		// https://github.com/micro/go-grpc/blob/master/examples/greeter/server/main.go
		service := microgrpc.NewService(
			micro.Name("my-server"),
			// https://github.com/micro/go-grpc/issues/4#issuecomment-369528973
			microgrpc.WithTLS(tlsConfig),
		)
		service.Init()
		service.Server().Init(server.Address("localhost:5678"))
		go func() {
			err = service.Run()
			if err != nil {
				log.Fatal(err)
			}
		}()

		// "plain" GRPC server
		// openssl.exe s_client -connect 127.0.0.1:1234
		// prints server cert
		grpcServer := grpc.NewServer(grpc.Creds(credentials.NewServerTLSFromCert(&certificate)))
		lis, err := net.Listen("tcp", ":1234")
		if err != nil {
			log.Fatal(err)
		}
		func() {
			err = grpcServer.Serve(lis)
			if err != nil {
				log.Fatal(err)
			}
		}()

		// block while the servers run
		select {}
	}

According to my go.mod my go-grpc version is v1.0.0.

**Comment by GeorgeBills** [comment]
Seems to be related to a buggy version of some package being pulled in - if we disable go modules (`$env:GO111MODULE='off'`), delete our go.mod and then go build again we pull the latest of every module into $GOPATH/pkg/ and TLS works again. But if we then restore our go.mod (`go mod init`) and rebuild (`go build .`) TLS goes back to broken. So some go.mod somewhere in our dependency tree must be pinning a broken version of some library that's doing the TLS.

**Comment by asim** [comment]
Sorry for the delayed response. Ok so basically we should update go.mod or find the issue related. I believe it's probably a version of go-plugins where the grpc client/server were wrongly initiating. 

I believe the fix occurred in 0.25.0 of go-plugins https://github.com/micro/go-plugins/releases/tag/v0.25.0

**Comment by GeorgeBills** [comment]
Hi Asim, thanks for the lead - slotting the following:

`replace github.com/micro/go-plugins => github.com/micro/go-plugins v1.0.0`

Into my top level go.mod (forcing the 1.0.0 release of go-plugins) fixes the issue. But without that line we get an older version of go-plugins with the bug, so it looks like some go.mod in our dependency tree must be stating it wants that older version.

**Comment by asim** [comment]
go mod has been updated so this should be resolved
