### ISSUE TITLE
Recompiling hello.proto breaks example

### ISSUE THREAD

**Issue by theOzzieRat** [micro/go-grpc#3]
If you recompile the hello.proto file with `protoc --go_out=plugins=grpc:. hello.proto` the server will no longer build as the structure of the proto.pb.go file is different to that contained within this repo.

Is there a way to fix this so it works again?

**Comment by asim** [comment]
We use a fork of protobuf with our own plugin. 

Please see https://github.com/micro/go-micro#install-protobuf

Then use `--go_out=plugins=micro`
