### ISSUE TITLE
go-grpc stream end with unexpected EOF error

### ISSUE THREAD

**Issue by SoaringTiger** [micro/go-grpc#5]
I have written a go-grpc server side stream client/server app. 
server side gist : https://gist.github.com/SoaringTiger/cc02769d00762a1e070308b99dcec8ec
client side gist: https://gist.github.com/SoaringTiger/eb6bea0f3f94936cdf90c5d676b919fe
proto gist: https://gist.github.com/SoaringTiger/9807b8c501a45c6010397316dd3e5b89

I found the client stream always end with "unexpected EOF" error.
Is it a bug?

**Comment by asim** [comment]
It's likely a bug in the stream handling somewhere. I'll have a look when I get a chance. The server should close the connection after the handler exits but I don't think this happens.
