### ISSUE TITLE
Doesn't support grpc stream?

### ISSUE THREAD

**Issue by pescaria** [micro/go-grpc#8]
rpc error: code = 4 desc = context deadline exceeded

**Comment by asim** [comment]
It does but you must increase the request timeout if you want a long live stream

**Comment by asim** [comment]
Example. When making a streaming request pass the client.WithRequestTimeout option.

```
import "github.com/micro/go-micro/client"

stream, err := c.Stream(context.Background(), client.WithRequestTimeout(time.Minute))
```
